In [1]:
#importing libraries
import numpy as np
import pandas as pd


In [2]:
# !pip3 install numpy --upgrade


**Question ** Numpy verson

In [3]:
print(np.__version__)

1.21.2


In [4]:
#version of pandas
print(pd.__version__)

1.1.5


In [5]:
#data_url
url = "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"
#load data
data = pd.read_csv(url)
data.head()

Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]

In [6]:
data.shape

(11914, 16)

In [7]:
data["Make"].value_counts()


Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
McLaren             5
Alfa Romeo          5
Bugatti   

In [8]:
bmw_mean = data[data.Make == "BMW"].mean()[7]

In [9]:
print(f"The mean of the BMW Make is: {bmw_mean}")

The mean of the BMW Make is: 61546.76347305389


In [10]:
include = data[data.Year >= 2015]
include

Make       Model  Year  ... city mpg  Popularity   MSRP
32     FIAT  124 Spider  2017  ...       26         819  27495
33     FIAT  124 Spider  2017  ...       26         819  24995
34     FIAT  124 Spider  2017  ...       26         819  28195
41      BMW    2 Series  2016  ...       23        3916  32850
42      BMW    2 Series  2016  ...       23        3916  38650
...     ...         ...   ...  ...      ...         ...    ...
11898   BMW          Z4  2015  ...       17        3916  56950
11899   BMW          Z4  2015  ...       17        3916  65800
11900   BMW          Z4  2016  ...       17        3916  57500
11901   BMW          Z4  2016  ...       22        3916  49700
11902   BMW          Z4  2016  ...       17        3916  66350

[5995 rows x 16 columns]

**Question 4**
Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [11]:
#Numbr of  missing values of Engine hp after and including 2015
include["Engine HP"].isna().sum()

51

**Question 5**





*   Calculate the average "Engine HP" in the dataset.
*   Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
*   Now, calcualte the average of "Engine HP" again.
Has it changed?


Round both means before answering this questions. You can use the round function for that:

In [12]:
#average of the Engine HP
eng_mean = data["Engine HP"].mean()

In [13]:
print(f"The mean is {eng_mean}")

The mean is 249.38607007176023


In [14]:
#copy of the series
eng_copy =  data["Engine HP"]

In [15]:
#fill the null values
eng_copy = eng_copy.fillna(eng_mean)

In [16]:
#mean after filling the null values
f_mean = eng_copy.mean()

In [17]:
#the means are the same after filling in th values
print(f"Original mean was {round(eng_mean)}, final mean is {round(f_mean)}")

Original mean was 249, final mean is 249


Question 6
* Select all the "Rolls-Royce" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
* Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Invert XTX.
* What's the sum of all the elements of the result?

In [18]:
#selecting all Rolls-Royce cars from the dataset
rolls = data[data.Make == "Rolls-Royce"]

In [19]:
#selecting some columns
rolls = rolls[["Engine HP", "Engine Cylinders", "highway MPG"]]

In [20]:
#dropping duplicates
rolls = rolls.drop_duplicates()

In [21]:
#checking shape
rolls.shape

(7, 3)

In [22]:
X = np.array(rolls)
type(X)

numpy.ndarray

In [23]:
#natrix-matrix multiplications
XTX = np.matmul(X.T,X)

In [24]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [25]:
#finding the inverse of the matrix
XTX = np.linalg.inv(XTX)

In [26]:
XTX

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [27]:
#sum of elements
np.sum(XTX)

0.032212320677486125

In [28]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [29]:
w = np.matmul(XTX,X.T)

In [30]:
w = np.matmul(w,y)

In [31]:
w

array([ 0.19989598, 31.02612262, 31.65378877])